### ISSUE TITLE
SyncML request failed

### ISSUE THREAD

**Issue by Skons** [Gerenios/AADInternals#1]
Upon following this Blog https://o365blog.com/post/mdm/ I hit a dead end with "Start-AADIntDeviceIntuneCallback -PfxFileName .\d03994c9-24f8-41ba-a156-1805998d6dc7-MDM.pfx -DeviceName "SixByFour". The error itself was not clear, but after adding $_ to the error "_throw "SyncML request failed: $($_ | out-string)"_" This pretty string popped up:
_SyncML request failed: Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again._

I could start internet explorer, but i added -UseBasicParsing to line 602. That solved my problem.

**Comment by NestoriSyynimaa** [comment]
Interesting. Which version of Windows you are running?
