### ISSUE TITLE
Get-AADIntAccessPackage* do not return results

### ISSUE THREAD

**Issue by nov3mb3r** [Gerenios/AADInternals#102]
When testing for enumeration of access package information i could not get results for the following snippets, although test packages exist inside the tenant:

- Get-AADIntAccessPackages
- Get-AADIntAccessPackageCatalogs
- Get-AADIntAccessPackageAdmins

However, the Get-AADIntAccessTokenForAccessPackages, works like a charm!
The role on the test account is Identity Governance Administrator

**Comment by NestoriSyynimaa** [comment]
Seem to be working for me. Did you used -Tenant <targettenant> parameter when getting the token?
