### ISSUE TITLE
'System.Xml.XmlDictionary' type not found

### ISSUE THREAD

**Issue by Kav7** [Gerenios/AADInternals#14]
Hello,

I installed the module, but after running the import command got this error:

`
Unable to find type [System.Xml.XmlDictionary].
At C:\Program Files\WindowsPowerShell\Modules\AADInternals\0.6.2\AzureADConnectAPI_utils.ps1:8 char:1
+ [System.Xml.XmlDictionary]$xml_dictionary = $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Xml.XmlDictionary:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
`

**Comment by NestoriSyynimaa** [comment]
Which OS you're running?

**Comment by Kav7** [comment]
Windows 10, 21H1

PS Version: 5.1.19041.1023

**Comment by Kav7** [comment]
Interesting thing is when I run this command after importing the module it works fine without error:
`[System.Xml.XmlDictionary]$xml_dictionary = $null`

But in a new PS session, if I try the same command it gives the same "Unable to find type [System.Xml.XmlDictionary]" error.

If I import the module twice, the second time there is no error

**Comment by NestoriSyynimaa** [comment]
I changed how the module is loading files so that seems to be the reason for that. I'll fix for the next release, thanks for reporting!
