### ISSUE TITLE
Join-AADIntDeviceToAzureAD creates device up in AAD but device itself never becomes AAD joined.

### ISSUE THREAD

**Issue by RODINOliver** [Gerenios/AADInternals#15]
Hey, I'm trying to use the 'Join-AADIntDeviceToAzureAD' command, as far as I can tell, it seems to be working.

I have tried using 'Get-AADIntAccessTokenForAADJoin -BPRT $BPRT' , 'Get-AADIntAccessTokenForAADJoin -SaveToCache' and 'Get-AADIntAccessTokenForAADJoin' for generating the token.

But I don't believe it is a permission issue.

Every time the command is ran a device is being created in AAD.

Most recent example -

PS Command Output:
![image](https://user-images.githubusercontent.com/92773448/140866523-7779b488-a38f-476f-98ea-a0051e033538.png)

AAD Device:
![image](https://user-images.githubusercontent.com/92773448/140866759-fe64a97c-5a2e-41cf-9921-bdd3858e0707.png)

However, at this stage, I was expecting I could reboot the device and it would be AAD Joined and ready to be signed into with an AAD account.

After a reboot that never occurs and when checking dsregcmd 'AzureAdJoined' is still 'NO'.
![image](https://user-images.githubusercontent.com/92773448/140866932-8624e532-361a-40a8-adf5-cd9fba66fc79.png)

I have also attempted to split the steps by performing the 'register' first then 'join' but the result was the same.

Am I missing something or?

**Comment by NestoriSyynimaa** [comment]
AADInternals can not currently be used to join "real" devices to AAD. It just follows the same procedure as the normal join process does and creates the certificate for "fake" device. The certificate represents the device, i.e., you can create a PRT with that and then get access tokens using the PRT. Resulting access tokens will have the deviceid claim.

I'm currently in the process of researching how to join "real" devices but that can take awhile.

**Comment by NestoriSyynimaa** [comment]
@RODINOliver, [AADInternals](https://o365blog.com/aadinternals/#join-aadintlocaldevicetoazuread) v0.6.6 supports this.

**Comment by RODINOliver** [comment]
Awesome! Can't wait to test it out.
