### ISSUE TITLE
Connecting to Partner Center

### ISSUE THREAD

**Issue by Aliyss** [Gerenios/AADInternals#17]
I tried connecting to the partner center.

Seems like I get a working Access Token when using the following:

```ps1
Get-AccessToken -Resource "https://api.partnercenter.microsoft.com" -ClientId "04b07795-8ddb-461a-bbee-02f9e1bf7b46"
```

Just thought you might want to know.

**Comment by NestoriSyynimaa** [comment]
Do you have problems with AADInternals when connecting to partner center? Or did you just find working resource/clientid?

**Comment by Aliyss** [comment]
Hiya sry. No I did not have any issues. I just found a working resource and client id

**Comment by NestoriSyynimaa** [comment]
Great to hear!
