### ISSUE TITLE
Setup Outlook profile

### ISSUE THREAD

**Issue by chervaliery** [Gerenios/AADInternals#18]
Hello,

I’am doing some tests and I’m wondering if it is possible to use the Access token retrieve from the Phishing for example, to setup an Outlook profile.

Thank you for your work on this script library.

**Comment by hidden-69** [comment]
+1

**Comment by hidden-69** [comment]
Or a working webclient to office.com

**Comment by NestoriSyynimaa** [comment]
Don't know about Outlook profile, as it's located in end point (if that's what you meant).

If this works as it should, you can modify the phishing function as needed to fetch a correct token. Just make sure that you've signed out from all browser sessions.
`$at = Get-AADIntAccessTokenForEXO -Resource "https://outlook.office.com" -UseDeviceCode`
`Open-AADIntOWA -AccessToken $at`
