### ISSUE TITLE
Documentation: Typo/update request for o365blog

### ISSUE THREAD

**Issue by Tinydile** [Gerenios/AADInternals#24]
I have several suggestions on o365blog's AADInternals reference.
https://o365blog.com/aadinternals/

* No mark for `Get-AADIntAccessTokenForSARA`
* Typo at table of `Get-AADIntAuthTokenForAADIAMAPI`, it should be `Get-AADIntAccessTokenForAADIAMAPI`
* Outlook related: 
  * `Open-AADIntOWA (O)` should be `(E)` not `(O)`?
  * `Get-AADIntAccessTokenForTeams` has `(T)` and `(TO)`? `Search-AADIntTeamsUser (TO)`
* How about to put the column `mark` for each entries on the table `Functionality` / `Playing with access tokens`

| Token/API                      | Function                                   | Mark    | Remarks                                                      |
| ------------------------------ | ------------------------------------------ | ------- | ------------------------------------------------------------ |
| No token needed                | N/A                                        | *       | example: Get-AADIntTenantid            |
| AAD Graph                      | Get-AADIntAccessTokenForAADGraph           | A       | Functions using AAD Graph access token.                      |
| MS Graph                       | Get-AADIntAccessTokenForMSGraph            | M       | Functions using MS Graph access token.                       |
| Pass Through Authentication    | Get-AADIntAccessTokenForPTA                | P       | Used when enabling/disabling PTA and Seamless SSO (Desktop SSO) |
| Azure Admin Portal             | Get-AADIntAccessTokenForAADIAMAPI          | Z       | Used when inviting guest users.                              |
| Exchange Online                | Get-AADIntAccessTokenForEXO                | E       | Used with Exchange Online and ActiveSync functions           |
| Support and Recovery Assistant | Get-AADIntAccessTokenForSARA               | SARA?   | Used with Support and Recovery Assistant functions           |
| SharePoint Online              | Get-AADIntSPOAuthenticationHeader          | S       | Used with SharePoint Online functions                        |
| OneDrive for Business          | New-AADIntOneDriveSettings                 | O       | Used with OneDrive for Business functions                    |
| Azure Core Management          | Get-AADIntAccessTokenForAzureCoreManagemnt | AC      | Used with Azure Core Management functions                    |
| Azure AD Join                  | Get-AADIntAccessTokenForAADJoin            | J       | Used with Azure AD join function                             |
| Azure Intune MD                | Get-AADIntAccessTokenForIntuneMDM          | N/A     | Used with Intune MDM functions                               |
| Azure Cloud Shell              | Get-AADIntAccessTokenForCloudShell         | C       | Used with Azure Cloud Shell                                  |
| (new)                          | Get-AADIntComplianceAPICookies             | CA      |                                                              |
| (new)                          | Get-AADIntAccessTokenForMSCommerce         | CM      |                                                              |
| (new)                          | Get-AADIntAccessTokenForMySignins          | MY      |                                                              |
| (new)                          | Get-AADIntAccessTokenForTeams              | T or TO | Set-AADIntTeamsStatusMessage (T)<br />Search-AADIntTeamsUser (TO) |
| (new)                          | Get-AADIntAccessTokenForTeams              | TO      |                                                              |
| (new)                          | Get-AADIntAccessTokenForPTA                | PTA     |                                                              |
| (new)                          | Get-AADIntAccessTokenForAdmin              | AD      |                                                              |
| (new)                          | Get-AADIntAccessTokenForMSPartner          | MP      |                                                              |

**Comment by NestoriSyynimaa** [comment]
Thanks for finding the typos and a very good improvement idea! I'll just need to figure it out what would be the best way to implement this. The whole doc has grown a quite large so I may need to restructure it totally.
