### ISSUE TITLE
HasCloudMX function incorrectly returns True

### ISSUE THREAD

**Issue by maxgrim** [Gerenios/AADInternals#29]
The HasCloudMX function should check whether the "*.mail.protection.outlook.com" MX record exists. However, in case this record does not exist, "False" is returned. When .Count is taken from this result this returns 1, which is greater than 0 and returns the whole function as True.

<img width="1419" alt="afbeelding" src="https://user-images.githubusercontent.com/2981208/178484629-92042014-63ff-489a-b344-429c0fa2f221.png">
<img width="1420" alt="afbeelding" src="https://user-images.githubusercontent.com/2981208/178484642-8d50847a-53d0-4e7a-af10-5d3eade58a82.png">

**Comment by maxgrim** [comment]
https://github.com/Gerenios/AADInternals/pull/30

**Comment by NestoriSyynimaa** [comment]
Thanks for reporting and PR!
