### ISSUE TITLE
Outdated Protocol list in Get-EASAutoDiscover function

### ISSUE THREAD

**Issue by celsogbezerra** [Gerenios/AADInternals#31]
The list of supported Protocols written in **Get-EASAutoDiscover** function are outdated. The application answer the following list of protocols when you send an unsupported value on Protocol parameter:

`Rest,ActiveSync,Ews,Substrate,SubstrateSearchService,AutodiscoverV1,SubstrateNotificationService,OutlookMeetingScheduler,OutlookPay,Actions,Connectors,ConnectorsProcessors,ConnectorsWebhook,NotesClient,OwaPoweredExperience,ToDo,Weve,OutlookLocationsService,OutlookCloudSettingsService,OutlookTailoredExperiences,OwaPoweredExperienceV2,Speedway,SpeechAndLanguagePersonalization,SubstrateSignalService,CompliancePolicyService`

It would be updated.

**Comment by NestoriSyynimaa** [comment]
Thanks, updated on the next release!
