### ISSUE TITLE
Invoke-AADIntReconAsGuest failed

### ISSUE THREAD

**Issue by kinomakino** [Gerenios/AADInternals#34]
Tested on different tenants, recognition as outsider and insider works, but not as guest . is it a permissions problem in Graph?

_Invoke-RestMethod : {"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException","Message":"Graph call failed with httpCode=Forbidden,
errorCode=Authorization_RequestDenied, errorMessage=Insufficient privileges to complete the operation., reason=Forbidden, correlationId_

thanks in advice !!!

**Comment by NestoriSyynimaa** [comment]
I assume the error is shown after prompting for the target tenant. In that case the target tenant guest user permissions are restricted. https://o365blog.com/post/quest_for_guest/#preventing
