### ISSUE TITLE
requesting user certificates error need decrypt

### ISSUE THREAD

**Issue by FlangvikAD** [Gerenios/AADInternals#36]
Hi, I am having some issues requesting user certificates using AADInternals, the issue code is https://github.com/Gerenios/AADInternals/blob/b4f082cca33452ae372f1ef0c780d425782c1156/PRT.ps1#L784
Microsoft currently encrypts the response body and cannot directly obtain the content of the x5c parameters. The original text is as follows: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oapxbc/eaf102b1-17d0-4988-b66b- 0f3c16193e9f

**Comment by NestoriSyynimaa** [comment]
I tried this and had no issues. Could you provide details how to reproduce?

**Comment by FlangvikAD** [comment]
Sorry, I wrongly located the code location, it is the user certificate instead of the device certificate, which is the Exchange Primary Refresh Token for User Authentication Certificate,
The original project is https://github.com/morRubin/PrtToCert

**Comment by NestoriSyynimaa** [comment]
So this was not AADInternals issue at all?

**Comment by FlangvikAD** [comment]
Thanks for your reply, it's not AADInternals' problem, sorry about that

**Comment by FlangvikAD** [comment]
不知道你有没有在AADInternals中加入请求用户证书功能的想法

**Comment by FlangvikAD** [comment]
I don't know if you have any idea of ​​adding the function of requesting user certificate in AADInternals

**Comment by NestoriSyynimaa** [comment]
Sure, I'll have a look at that. Shouldn't be that difficult.
