### ISSUE TITLE
Mimikatz listed

### ISSUE THREAD

**Issue by greenlighttec** [Gerenios/AADInternals#45]
![image](https://user-images.githubusercontent.com/16570127/203999658-56641c1c-0c9c-491b-9fcb-2df7a478924a.png)

Our SOC lit up when we were running this on our systems because of a keyword match. Doesn't seem to have anything malicious anywhere else but seriously, is this line really necessary? And with this name?

**Comment by NestoriSyynimaa** [comment]
Hah, not needed 😁. Removing..
