### ISSUE TITLE
No MFA Prompt for Get-AADIntAccessTokenForAADGraph

### ISSUE THREAD

**Issue by firefox15** [Gerenios/AADInternals#47]
I might be missing something obvious, but I cannot seem to get the Azure access token for tenants that require MFA.   I get the Modern Authentication prompt when I execute the following cmdlet, but it simply doesn't ask me for an MFA code after email and password, so then it gives me an error.

Sample code:

`$accessToken = Get-AADIntAccessTokenForAADGraph -Resource urn:ms-drs:enterpriseregistration.windows.net`

Response after email and password are prompted via Modern Auth:

> Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access . . . 

Is there anyway to force the authentication prompt to allow me to enter the MFA code?

**Comment by firefox15** [comment]
For whatever reason, it appears that "Enforcing" the MFA prompt from Azure AD allows the prompt to come up when running the cmdlet.  While this is weird to me, it does work, so I'm closing this.

**Comment by reubano** [comment]
@firefox15 how did you resolve this issue exactly?

**Comment by firefox15** [comment]
> [@firefox15](https://github.com/firefox15) how did you resolve this issue exactly?

It's been a while, but I believe I just needed to enforce MFA on that user within the per-user MFA portal.
