### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by fraga** [Gerenios/AADInternals#50]
The text to speech examples do not work. Windows 10 machine.

```Powershell
Get-AADIntAccessTokenForOneNote -SaveToCache
Start-AADIntSpeech -Text "Three Swedish switched witches watch three Swiss Swatch watch switches. Which Swedish switched witch watch which Swiss Swatch watch switch?" -Language "en-GB" -PreferredVoice Male
```

Tracing with Fiddler and it looks like I do have 200 for both content model and get speech
```
POST /learningtoolsapi/v2.0/getcontentmodelforreader HTTP/1.1
POST /learningtoolsapi/v2.0/GetSpeech HTTP/1.1
```
Before I start hunting down the issue on my machine was wondering if someone else could please run the sample above and tell me it works. It would be appreciated.

Thank you very much

**Comment by NestoriSyynimaa** [comment]
Thanks!
