### ISSUE TITLE
Error when attempting to import module in powershell core

### ISSUE THREAD

**Issue by enthusedcoder** [Gerenios/AADInternals#58]
Hello.  I wanted to report an error that occurs when attempting to import the aadinternals module into a powershell core session.  The error is:

```
SetValueInvocationException: Exception setting "SecurityProtocol": "The requested security protocol is not supported."
```

![image](https://github.com/Gerenios/AADInternals/assets/127647168/b6fa07c4-fa4f-4868-8630-b4c3f37d0c15)

This error does not occur when using windows powershell

**Comment by NestoriSyynimaa** [comment]
Fixed in v0.9.0
