### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by thelordofscrubs** [Gerenios/AADInternals#6]
PS C:\WINDOWS\system32> $creds = Get-Credential

 $prtKeys = Get-UserAADIntPRTKeys -PfxFileName .\ff78b0a3-5348-4e93-ba6d-b043540acd7c.pfx -Credentials $cred

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Get-UserAADIntPRTKeys : The term 'Get-UserAADIntPRTKeys' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:4 char:12
 $prtKeys = Get-UserAADIntPRTKeys -PfxFileName .\ff78b0a3-5348-4e93-ba ...
            ~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : ObjectNotFound: (Get-UserAADIntPRTKeys:String) [], CommandNotFoundException
 FullyQualifiedErrorId : CommandNotFoundException



Running into this error while attempting to debug a PRT issue. All of the other commands in the module have worked great so far, and I would GREATLY appreciate any assistance.

**Comment by NestoriSyynimaa** [comment]
I think you miss spelled the command. The correct would be:
`$prtKeys = Get-AADIntUserPRTKeys -PfxFileName .\ff78b0a3-5348-4e93-ba6d-b043540acd7c.pfx -Credentials $cred`

**Comment by thelordofscrubs** [comment]
![image](https://user-images.githubusercontent.com/47277534/111210396-332dd980-859b-11eb-922f-7eed9d3261aa.png)

I see, I notice now the header of this section shows the correct spelling. The issue seems to be that your blogs example has it wrong.

**Comment by NestoriSyynimaa** [comment]
Thanks for noticing, fixed the documentation.
