### ISSUE TITLE
Federated identities are not supported

### ISSUE THREAD

**Issue by codeitch** [Gerenios/AADInternals#60]
Since the new version 0.9.0, there seems to be this exception following an authentication attempt:

Exception: C:\Program Files\WindowsPowerShell\Modules\AADInternals\0.9.0\AccessToken_utils.ps1:2885
Line |
2885 |              throw "Federated identities are not supported."
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Federated identities are not supported.

**Comment by NestoriSyynimaa** [comment]
Correct, it is not implemented yet. Will try to get it to the next release.

**Comment by Kor1134** [comment]
Do you have an estimated timetable to implement federated identities?

I'm currently limited to 30-day tokens as that is the extent ICD will allow, and we are migrating thousands of devices from local domains to Azure AD.  I can't generate a BPRT with my federated ID, and I desperately need this feature.

**Comment by NestoriSyynimaa** [comment]
Due to various reasons, I won't be implementing this to AADInternals. It would be relatively easy to support ADFS, but there are so many options out there..

However, you can authenticate using v0.8.x versions, they should be working just fine.
