### ISSUE TITLE
Rename Repo from AADInternals to MSEntraIDInternals 🤣

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Gerenios/AADInternals#63]
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-is-becoming-microsoft-entra-id/ba-p/2520436

**Comment by NestoriSyynimaa** [comment]
[🔗](http://entraidinternals.com)

**Comment by michaelmsonne** [comment]
Haha @NestoriSyynimaa nice one! Then no one can´t say that is not done 😉👍
