### ISSUE TITLE
Possible authentication issue with “TROOPERS23 edition”.

### ISSUE THREAD

**Issue by rick-trey** [Gerenios/AADInternals#65]
I'm new to AADInternals, so this may be something I'm doing?

I'm trying to run Get-AADIntAccessTokenForGraph to get a BPRT token for bulk AzureAD domain join for devices.   However I get the following set of messages:
![image](https://github.com/Gerenios/AADInternals/assets/140054428/1a8c4d14-f6fe-488d-994c-c90d27ea9563)

the user account used in the above screen capture is a Global Admin, but I have tried with a standard user with the same results.   I have also tried on different machines.

**Comment by NestoriSyynimaa** [comment]
I wasn't able to reproduce this. Could be something that I already fixed in next version I'll be releasing during the DefCon.
