### ISSUE TITLE
Dependencies - List

### ISSUE THREAD

**Issue by PracticalCode** [Gerenios/AADInternals#66]
Good Evening,

I was looking at your project, and I've two questions:

#1. )  Where is the function [Create-LoginForm] defined? .. it's used in the following locations:

.\AccessToken.ps1
  2232,15:         $form=Create-LoginForm -Url $url -auth_redirect $auth_redirect

.\AzureManagementAPI_utils.ps1
  603,17:         $form = Create-LoginForm -Url $url -auth_redirect $auth_redirect

.\ComplianceAPI.ps1
  35,17:         $form = Create-LoginForm -Url $url -auth_redirect "https://login.microsoftonline.com/kmsi"

.\SPO_utils.ps1
  88,17:         $form = Create-LoginForm -Url $url -auth_redirect $auth_redirect -Headers "Cookie: $cookieHeaderValue"

C:\dev\ps1\AzurePurview\ComplianceAPI.ps1
  36,17:         $form = Create-LoginForm -Url $url -auth_redirect "https://login.microsoftonline.com/kmsi"

#2.)  On your site, https://aadinternals.com/aadinternals/, you state, ""The module is a plain PowerShell script module...""; however, your project also contains a number of DLLs in the folder [./DSInternals] ...

i.e. ===

.\DRS_Utils.ps1
  221,43:             Add-Type -Path "$PSScriptRoot\DSInternals\NDceRpc.Microsoft.dll"
  222,43:             Add-Type -Path "$PSScriptRoot\DSInternals\DSInternals.Replication.Interop.dll"
  223,43:             Add-Type -Path "$PSScriptRoot\DSInternals\DSInternals.Replication.dll"

... where is the source code for them and/or a description of which methods are dependent upon them?

Thanks,

George

PS  Note this is not to take away from all of the hard work you've done, & I greatly appreciate you're sharing your project.  Thanks.

**Comment by NestoriSyynimaa** [comment]
1. Create-LoginForm function doesn't exist anymore in version 0.9.0 and later. The source of previous version is here: https://github.com/Gerenios/AADInternals/blob/49d58f79924f1bf946db917f28ca17bba2509c1e/AccessToken_utils.ps1#L1199
2. The most of the code is pure PS, but some functionality couldn't be done via PS so yes, there are some dlls. The source code of files under DSInternals is here: https://github.com/Gerenios/DSInternals
