### ISSUE TITLE
Install getting blocked by AV

### ISSUE THREAD

**Issue by Kav7** [Gerenios/AADInternals#67]
hello,

I have BitDefender antivirus installed and its blocking the install, as per this screenshot:
![image](https://github.com/Gerenios/AADInternals/assets/4002197/822996af-5f11-4dcb-8f31-66901b69c0b0)

The problem with the install is that everytime it is run, the folder name after ...\temp\ is random, so its impossible to add an exclusion for the path on the AV software.

Any options or ideas?

**Comment by NestoriSyynimaa** [comment]
You could manually copy all files to C:\Program Files\WindowsPowerShell\Modules\AADInternals\<version>\ and exclude the whole AADInternals folder
