### ISSUE TITLE
Join-AADIntDeviceToIntune doesn't change device status to complaint

### ISSUE THREAD

**Issue by pawp81** [Gerenios/AADInternals#7]
Running Join-AADIntDeviceToIntune generates MDM certificates. However what is required to do change device state to complaint? The compliance policy assigned to the device is in the "Not evaluated" state. How to utilize received certificates?
Morever after enrolling device to Intune, its name in Intune is not the one specified by DeviceName parameter of Join-AADIntDeviceToIntune. Instead the name is in the format: username_OS_date
![image](https://user-images.githubusercontent.com/47076035/110902080-943c7f80-8305-11eb-938f-19dd5c650c06.png)

**Comment by NestoriSyynimaa** [comment]
With the MDM certificates, you can connect to Intune and pretend to be the device.

You need to run the following command (replace the certificate name with your own). It will set the name and MIGHT set the device compliant. The compliancy policies always depends on the Intune configuration.
`Start-AADIntDeviceIntuneCallback -PfxFileName .\d03994c9-24f8-41ba-a156-1805998d6dc7-MDM.pfx -DeviceName "SixByFour"`
