### ISSUE TITLE
Allow suppression of import-module message

### ISSUE THREAD

**Issue by 3pichaxz0r** [Gerenios/AADInternals#70]
When importing the module | out-null is ignored and messages are still written to the console. Proposed change would be to change use from write-host to something that supports out-null

**Comment by 3pichaxz0r** [comment]
When the module is loaded and it attempts to change the console window title it also throws an error when run in a non-interactive environment.

**Comment by NestoriSyynimaa** [comment]
The doesn't seem to be a good alternative for Write-Host at the moment :(
I surrounded setting the title in try-catch block.
