### ISSUE TITLE
Authentication issue after updating to 0.9.1

### ISSUE THREAD

**Issue by chrisnelmes** [Gerenios/AADInternals#72]
Get-AADIntAccessTokenForAADGraph -Resource urn:ms-drs:enterpriseregistration.windows.net -SaveToCache

Cannot index into a null array.
At C:\Users\Chris.Nelmes\OneDrive - Harmonic
Directory\Documents\WindowsPowerShell\Modules\aadinternals\0.9.1\CommonUtils.ps1:2734 char:9
+         $redirect = $Response.Headers["Location"]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

You cannot call a method on a null-valued expression.
At C:\Users\Chris.Nelmes\OneDrive - Harmonic
Directory\Documents\WindowsPowerShell\Modules\aadinternals\0.9.1\CommonUtils.ps1:2741 char:13
+             $redirect = $response.content.Replace("\u0026","&")
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Authorization code not received!
At C:\Users\Chris.Nelmes\OneDrive - Harmonic
Directory\Documents\WindowsPowerShell\Modules\aadinternals\0.9.1\CommonUtils.ps1:2755 char:13
+             Throw "Authorization code not received!"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Authorization code not received!:String) [], RuntimeException
    + FullyQualifiedErrorId : Authorization code not received!

Works in 0.8.2

**Comment by NestoriSyynimaa** [comment]
Should work in v0.9.2

**Comment by NestoriSyynimaa** [comment]
*v0.9.3

**Comment by chrisnelmes** [comment]
Thanks @NestoriSyynimaa, 0.9.1 is the latest available via PSGallery. Will the latest version be deployed to PSGallery?

**Comment by NestoriSyynimaa** [comment]
Yes, later today
