### ISSUE TITLE
Cannot login to tenant with Get-AADIntAccessTokenForAADGraph

### ISSUE THREAD

**Issue by exproject** [Gerenios/AADInternals#78]
When trying to authenticate and get a token, the following error is thrown

![image](https://github.com/Gerenios/AADInternals/assets/16395586/9b32e7aa-66da-41ff-ba55-28c9f0316893)

Is it expected to be able to work with a Microsoft sign in page type sign in, or does it need to be username and pass or a TAP to sign in?

**Comment by NestoriSyynimaa** [comment]
Try the latest version, what ever was the reason, it is likely fixed.
