### ISSUE TITLE
Set-AADIntDeviceCompliant Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by pawp81** [Gerenios/AADInternals#8]
After enrolling device to Intune if I try to set it as compliant with Set-AADIntDeviceCompliant I receive following error:
Invoke-RestMethod : {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"7f1ca352-fcb8-4f69-bbef-f47eda0beb69","date":"2021-03-24T18:37:56"}}
At C:\Program Files\WindowsPowerShell\Modules\AADInternals\0.4.6\MDM.ps1:795 char:9
+         Invoke-RestMethod -Method Patch -Uri "https://graph.windows.n ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

What permissions user needs to have to run Set-AADIntDeviceCompliant?

**Comment by uzmest** [comment]
Same error here as a GA : 
Invoke-RestMethod : {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the
operation."},"requestId":"3c9XXXXXXX6e","date":"2021-05-07T18:20:54"}}
Au caractère C:\Program Files\WindowsPowerShell\Modules\AADInternals\0.4.6\MDM.ps1:795 : 9
+         Invoke-RestMethod -Method Patch -Uri "https://graph.windows.n ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by NestoriSyynimaa** [comment]
Sorry for the late response, I didn't receive any notifications due to misconfigured settings. Anyways, I'll have a look at this some point later this week. Global Admin should have all permissions, so probably Microsoft have made some changes. I assume they have limited this to certain clients (and/or custom apps).

**Comment by notna92** [comment]
i believe we are still experiencing the above issues. i tried to set compliance on a device in aad and the same error was shown 

Invoke-RestMethod : {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation

just wondering if there was anything different that's required to be done now?
