### ISSUE TITLE
Malware Detection?

### ISSUE THREAD

**Issue by kckenterprises** [Gerenios/AADInternals#98]
![Screenshot 2024-08-06 124659](https://github.com/user-attachments/assets/beb2ba92-8bf7-42ed-9d7a-a9b4d7fa2d96)
![Screenshot 2024-08-06 124746](https://github.com/user-attachments/assets/4a2fe405-a2da-41fb-a513-4030fc302f20)

Getting multiple detections when installing this PS module.

Is this to be expected?

**Comment by weyCC81** [comment]
Microsoft Defender is also flagging the following files during the Installation for me:
- AADInternals.png = Trojan:Win32/Malgent!MSR
- Win32Ntv.dll  = Backdoor:MSIL/SuspAdsyncBin.D

```
Install-Module AADInternals
# PackageManagement\Install-Package : Package 'AADInternals' failed to be installed because: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

Would it be possible to move the into a separated module?
```
Install-Module AADInternals.Beta
Install-Module AADInternals.Experimental
```

**Comment by NestoriSyynimaa** [comment]
https://x.com/DrAzureAD/status/1838527114632401382

**Comment by Mike-Crowley** [comment]
Thanks! I suspected as much, but thank you for confirming they are legitimate and not dangerous to users of the PowerShell module.
