### ISSUE TITLE
Get-AADIntComplianceAPICookies fails with 'Create-LoginForm' is not recognized

### ISSUE THREAD

**Issue by TotallyTroll** [Gerenios/AADInternals#99]
Hello,

Trying to obtain cookie and x-xsrf tokens via [ComplianceAPI.ps1](https://github.com/Gerenios/AADInternals/blob/master/ComplianceAPI.ps1) , running _$cookies = Get-AADIntComplianceAPICookies_ command. Still next error occur:
Create-LoginForm : The term 'Create-LoginForm' is not recognized as the name of a cmdlet, function, script file, or
operable program.

Steps to reproduce:
1. Install-Module AADInternals
2. Import-Module AADInternals
3. $cookies = Get-AADIntComplianceAPICookies
Initially it fails with an error that -MaximumRedirection limit reached. So I've changed this to -MaximumRedirection 5 within module's ComplianceAPI.ps1 file.
4. $cookies = Get-AADIntComplianceAPICookies
Now it fails with mentioned error:
Create-LoginForm : The term 'Create-LoginForm' is not recognized as the name of a cmdlet, function, script file, or
operable program.

Am I missing some dependent module installed?

**Comment by bastienperez** [comment]
After reviewing the version history, the function  `Create-LoginForm` was removed in version 0.9.0, likely due to the redesign for PowerShell 7 introduced by @NestoriSyynimaa.

So, we can't use this function for now.

**Comment by NestoriSyynimaa** [comment]
Let me have a look at this case!

**Comment by NestoriSyynimaa** [comment]
Removed Get-AADIntComplianceAPICookies and changed Search-AADIntUnifiedAuditLog to use access token instead.
